name: BoxLang Snapshots

on:
  push:
    branches:
      - development

#Cancel running builds if another push to branch is made while this build is running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  ##########################################################################################
  # Format Source Code
  ##########################################################################################
  format:
    name: Code Auto-Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Verify Code Formatting
        run: ./gradlew spotlessApply --stacktrace

  #############################################
  # Build Snapshot Release
  #############################################
  build:
    uses: ./.github/workflows/release.yml
    needs: [tests, format]
    secrets: inherit
    with:
      snapshot: true
