name: BoxLang Test Suites

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  tests:
    name: Test BoxLang
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        jdkVersion: [ "17" ]
        experimental: [false]
        include:
          - jdkVersion: "20"
            experimental: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdkVersion }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.2"

      # TODO: Add the compiler once it's stable
      - name: Build & Test The Runtime
        run: |
          cd runtime
          gradle test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: |
            runtime/build/reports/tests/**
            runtime/build/test-results/**

  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: tests
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/**/*.xml
