name: Trigger Docker Image Creation

on:
  workflow_run:
    workflows: [BoxLang Snapshots]
    types: [completed]
    branches:
      - "development"

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Workflow docker-bx Repo
        run: |
          # Set the required variables
          repo_owner="ortus-solutions-private"
          repo_name="docker-bx"
          event_type="trigger-workflow"
          service=release"
          bx_version="1.0.0"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows/release.yml/dispatches \
            -d "{\"ref\": \"main\", \"inputs\": {\"version\": \"$bx_version\"}}"
